### ISSUE TITLE
Sharing of single-cell pre-trained embeddings

### ISSUE THREAD

**Issue by ChengHsiuChi** [AIH-SGML/mixmil#10]
Hi, thank you again for the previous explanation and this great work.

I have been through your paper, and I am interested in implementing the model on BBBC021 dataset.
Would it be possible to share the obtained single-cell representations?

That would be really appreciated :)!

Best regards,
Hsiuchi

**Comment by allepalma** [comment]
Hi @ChengHsiuChi,

Thank you again for your interest in our work. Please, find the featurized images at the following link:

https://drive.google.com/file/d/1LEW74HUaJ2BMlPMmUlYMrsCFTmbpR2Rd/view?usp=drive_link

The features are saved as an AnnData object (https://anndata.readthedocs.io/en/latest/) which you can read and inspect using the Scanpy package (https://scanpy.readthedocs.io/en/stable/).

Let us know if we can help you any further!
