### ISSUE TITLE
Very long waiting time for the init setep

### ISSUE THREAD

**Issue by HelloWorldLTY** [AIH-SGML/mixmil#12]
Hi, I found that the initial step of this method is superly long for me. I have been waiting for one hour. Any suggestions here? Are they related to data scales? I have 276400 instances for training here.

**Comment by jan-engelmann** [comment]
Hi,
Can you provide more detail? Which code are you running? What's your data size and dimensionality?
If you are standardizing the whole dataset that can take a while.
Profiling your code would help you figure out where most of the compute time is spent. 
Cheers!

**Comment by HelloWorldLTY** [comment]
Hi, thanks. I have ~ 2000 bags, but 28000+ features. Do you think the number of features will be a big problem here?

Also, I cannot fit my current model with one A100 80GB GPU.

**Comment by jan-engelmann** [comment]
Hi!
in the paper we argue for unsupervised representation learning to reduce the dimensionality.
What type of data is this? If it's sc-RNAseq I'd recommend for example scVI to reduce the dimensionality first.

**Comment by HelloWorldLTY** [comment]
Ok, thanks. I tried to reduce the dimensions to 256 dims but still had the same issue. Maybe I can look for other tools for dimension reduction.
