### ISSUE TITLE
Request: Dataset & Notebook for Single Cell Genomics Application on OneK1K Dataset

### ISSUE THREAD

**Issue by Chloe-Shen** [AIH-SGML/mixmil#9]
Description:
Exciting application spotted in single-cell genomics! Requesting access to dataset and notebook related to the OneK1K dataset. Would greatly aid further exploration and analysis. Thank you!

Regards,
Chloe

**Comment by jan-engelmann** [comment]
Hi Chloe,

thanks for reaching out!

You can find the expression count data and raw genotype data [here on GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE196830).
You would, however, have to process and impute the genotype data yourself.

Since genotype data is sensitive and the [OneK1K authors](https://onek1k.org/) decided against sharing the processed genotypes, I can unfortunately not make them public. You could reach out to them though.

Cheers,
Jan

**Comment by rpeys** [comment]
Hi Jan, I was coming here to GitHub to ask for this same notebook. Would it be possible to provide notebooks that we could run if we obtain the processed data? Even if we can't reproduce the analysis ourselves until we get access to the processed data, it would be really helpful to see your experiments and results in detail. 

Also, are you able to comment on which covariates were most predictive for the OneK1K dataset? I would imagine the fixed effects (especially PCs of genetic info) may have been more predictive than the single cell data. Did you run a baseline with only the fixed effects? If so, I would be curious what the results were. 

Thanks again for the interesting work!

**Comment by jan-engelmann** [comment]
Hi Rebecca,

Unfortunately, I have not yet had the time to provide a user-friendly version of our code.
I can do that if there's interest from a few more people. @others, please react with 👍  if you're interested.

> Also, are you able to comment on which covariates were most predictive for the OneK1K dataset? I would imagine the fixed effects (especially PCs of genetic info) may have been more predictive than the single cell data. Did you run a baseline with only the fixed effects? If so, I would be curious what the results were.

I have not yet tried that. But please note that we never predict from genetic PCs, we solely account for them as fixed effects. The predictive performance we report comes from the single-cell embeddings.

Let me know if you have any further questions.

Best regards,
Jan
